Repository Pride-Points/Front-End, pull requests merged in 2023-11, with the labels that each got.

#9 Integracao cadastros back-end
  package-lock.json
  package.json
  src/api/api.js
  src/components/Cadastros/Cadastro.jsx
  src/components/Cadastros/CadastroDire.css
  src/components/Cadastros/CadastroDire.jsx
  src/components/Login/Login.jsx
  src/index.js
  src/pages/CadastroEmpresa.js
  src/pages/CadastroUsuario.js
  src/pages/Configuracoes.js
Labels: Code Review

#11 Mergeando tela da ju
  src/assets/Fechar.png
  src/assets/FotoPadrao.png
  src/assets/IconePesquisa.png
  src/assets/PointCinze.png
  src/assets/PointCinze.svg
  src/assets/Pride.png
  src/assets/backgroundReviews.png
  src/assets/estrela.png
  src/assets/icon-calendario.svg
  src/assets/icon-configuracoes.svg
  src/assets/icon-estrela.svg
  src/assets/icon-helpdesk.svg
  src/assets/icon-mapa.svg
  src/assets/icon-sair.svg
  src/assets/icon_filter.svg
  src/assets/icone-Pointer.png
  src/assets/img-avaliacao1.png
  src/assets/img-evento1.png
  src/assets/lupa-icon.svg
  src/assets/starbucks.png
  src/components/TelasUsuario/Avaliacoes.jsx
  src/components/TelasUsuario/Eventos.jsx
  src/components/TelasUsuario/HeaderUsuario/HeaderUsuario.jsx
  src/components/TelasUsuario/HeaderUsuario/headerUsuario.css
  src/components/TelasUsuario/Home-eventos.jsx
  src/components/TelasUsuario/Home-locais.jsx
  src/components/TelasUsuario/Maincontent/CardReview.jsx
  src/components/TelasUsuario/Maincontent/CardUsuario.jsx
  src/components/TelasUsuario/Maincontent/MainContent.jsx
  src/components/TelasUsuario/Maincontent/SearchContent.jsx
  src/components/TelasUsuario/Maincontent/mainContent.css
  src/components/TelasUsuario/Maincontent/searchContent.css
  src/components/TelasUsuario/MapSection.jsx
  src/components/TelasUsuario/MenuLateral/MenuLateral.jsx
  src/components/TelasUsuario/MenuLateral/menuLateral.css
  src/components/TelasUsuario/PopUp/PopUpLocais.jsx
  src/components/TelasUsuario/PopUp/popUpEventos.css
  src/components/TelasUsuario/PopUp/popUpEventos.jsx
  src/components/TelasUsuario/PopUp/popUpLocais.css
  src/components/TelasUsuario/avaliacoes.css
  src/components/TelasUsuario/eventos.css
  src/components/TelasUsuario/home-eventos.css
  src/components/TelasUsuario/home-locais.css
  src/pages/Avaliacoes.js
  src/pages/Eventos.js
  src/pages/Home.js
  src/routes.js
Labels: Code Review, Em andamento

#12 Integracao cadastros back
  src/assets/icon-back.png
  src/components/Cadastros/Cadastro.jsx
  src/components/Cadastros/CadastroDire.css
  src/components/Cadastros/CadastroDire.jsx
  src/components/telaConfigurações/configuracoes.js
  src/components/telaConfigurações/conteudoPrincipal.css
  src/components/telaConfigurações/conteudoPrincipal.jsx
  src/components/telaConfigurações/forms.css
  src/components/telaConfigurações/forms.jsx
  src/components/telaConfigurações/header.css
  src/components/telaConfigurações/header.jsx
  src/components/telaConfigurações/jsconfig.json
  src/components/telaConfigurações/menuLateral.css
  src/components/telaConfigurações/menuLateral.jsx
  src/components/telaExplorador/CommentSection.jsx
  src/components/telaExplorador/Map.jsx
  src/components/telaExplorador/map.css
  src/pages/CadastroUsuario.js
  src/routes.js
Labels: Code Review

#13 Mergeado tela do joao
  src/assets/avalBlack.svg
  src/assets/dashBlack.svg
  src/assets/eventosBlack.svg
  src/assets/eventosColor.svg
  src/assets/icon-calendar.svg
  src/assets/icon-help.svg
  src/assets/icon-person.svg
  src/assets/people.svg
  src/components/Eventos/Evento.jsx
  src/components/Eventos/Eventos.css
  src/pages/EventosEmpresa.js
  src/routes.js
Labels: Code Review

#14 Tela do enzo Dashboard mergeada
  package-lock.json
  package.json
  src/assets/avatar.svg
  src/assets/icon-avaliacoes.svg
  src/assets/icon-chart.svg
  src/assets/icon-clipboard.png
  src/assets/icon-comentarios.svg
  src/assets/icon-config.svg
  src/assets/icon-cupons.svg
  src/assets/icon-eventos.svg
  src/assets/icon-filtro.svg
  src/assets/icon-media.svg
  src/components/dashboard/DashboardBar.jsx
  src/components/dashboard/DashbpardPizza.jsx
  src/components/dashboard/dash-content.jsx
  src/components/dashboard/dash.css
  src/components/dashboard/dash.jsx
  src/components/headerUsuario/HeaderUsuario.jsx
  src/components/headerUsuario/headerUsuario.css
  src/components/menuLateral/MenuLateral.jsx
  src/components/menuLateral/menuLateral.css
  src/routes.js
Labels: Code Review

#16 Ajustes index, telas de cadastro
  src/api/api.js
  src/assets/image-explorar.png
  src/assets/image-login.png
  src/components/Cadastros/CadastroDire.jsx
  src/components/Card/Card.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/footer.css
  src/components/Home/Home.jsx
  src/components/Home/MainSection.jsx
  src/components/Home/UserSectionDefault.jsx
  src/components/Login/Login.jsx
  src/pages/CadastroEmpresa.js
  src/pages/CadastroUsuario.js
  src/pages/LandingPage.js
Labels: Code Review

#17 tela de funcionários
  package-lock.json
  package.json
  src/assets/Vector.svg
  src/assets/downloadIcon.svg
  src/assets/urser-cricle-add.svg
  src/assets/user2.svg
  src/assets/userCard.svg
  src/assets/🦆 icon _user circle plus_.svg
  src/components/telaFuncionarios/Funcionarios.jsx
  src/components/telaFuncionarios/funcionarios.css
  src/pages/Funcionarios.js
  src/routes.js
Labels: Code Review

#18 Tela empresa avaliacao
  src/assets/avalBlack.svg
  src/assets/balãoAmarelo.svg
  src/assets/balãoVerde.svg
  src/assets/balãoVermelho.svg
  src/assets/icon-anserwered-false.svg
  src/assets/icon-answered.svg
  src/assets/icon-perfil.svg
  src/assets/icon-sair copy.svg
  src/assets/logo-dark copy.svg
  src/components/AvaliacaoEmpresa/AvaliacaoEmpresa.jsx
  src/components/AvaliacaoEmpresa/avaliacao.js
  src/components/AvaliacaoEmpresa/avaliacaoEmpresa.css
  src/components/AvaliacaoEmpresa/commentModel.js
  src/components/AvaliacaoEmpresa/modalResposta.jsx
  src/components/AvaliacaoEmpresa/preenchidoColuna.jsx
  src/components/AvaliacaoEmpresa/starRating.js
  src/components/menuLateral/HeaderMenuLateral.jsx
  src/components/menuLateral/headerMenuLateral.css
  src/pages/AvaliacaoEmpresa.js
  src/routes.js
Labels: Code Review

#20 Tela empresa funcionarios
  package-lock.json
  src/assets/defaultIcon.png
  src/assets/excel.png
  src/assets/icon _user circle plus_.svg
  src/assets/imgFuncionario.png
  src/assets/text.png
  src/components/Card/Card.jsx
  src/components/Eventos/Evento.jsx
  src/components/Eventos/Eventos.css
  src/components/telaFuncionarios/CardFuncionario.jsx
  src/components/telaFuncionarios/Funcionarios.jsx
  src/components/telaFuncionarios/funcionarios.css
Labels: Code Review

#22 prescisa de ajustes
  src/assets/icon modal event.png
  src/assets/img-evento.png
  src/assets/trash.svg
  src/components/Eventos/CardReview.jsx
  src/components/Eventos/CardUsuario.jsx
  src/components/Eventos/Eventos.css
  src/components/Eventos/EventosEmpresa.jsx
  src/components/Eventos/MainContentEmpresa.jsx
  src/components/Eventos/SearchContentEmpresa.jsx
  src/components/Eventos/mainContent.css
  src/components/Eventos/searchContentEmpresa.css
  src/pages/EventosEmpresa.js
  src/routes.js
Labels: Codigo Bugado, Code Review, Resolução de erro, Em andamento

#29 integrando ainda, mergeando para deixar a Homologação atualizada
  src/assets/PESOSOSOA.svg
  src/assets/PointerLGBT+.svg
  src/assets/PointerLGBT.png
  src/assets/Starrrrr.svg
  src/assets/starrrpreenchida.svg
  src/components/TelasUsuario/Eventos.jsx
  src/components/TelasUsuario/Home-locais.jsx
  src/components/TelasUsuario/MapSection.jsx
  src/components/TelasUsuario/Modal/modal.css
  src/components/TelasUsuario/Modal/modal.jsx
  src/components/TelasUsuario/PopUp/PopUpLocais.jsx
  src/components/TelasUsuario/PopUp/popUpAvaliacoes.css
  src/components/TelasUsuario/PopUp/popUpAvaliacoes.jsx
  src/components/TelasUsuario/PopUp/popUpEventosGeral.jsx
  src/components/TelasUsuario/PopUp/popUpLocais.css
Labels: Code Review, Em andamento
